In [1]:


%pip install otter-grader==5.5.0
%cd /content/gdrive/MyDrive/colab-materials-data8-notebooks/materials-sp22-colab/hw/hw05/

# Initialize Otter
import otter
grader = otter.Notebook(colab=True)

Requirement already satisfied: otter-grader==5.5.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (5.5.0)
Requirement already satisfied: nbformat in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (5.10.4)
Requirement already satisfied: ipython in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (8.18.1)
Requirement already satisfied: dill in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (0.4.1)
Requirement already satisfied: astunparse in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (1.6.3)
Requirement already satisfied: ipywidgets in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (8.1.8)
Requirement already satisfied: pandas in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (2.3.3)
Requirement already satisfied: click in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (8.1.8)
Requirement already satisfied: requests in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (2.32.5)
Requirement already satisfied: PyYAML in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (6.0.3)
Requirement already satisfied: jinja2 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (3.1.6)
Requirement already satisfied: fica>=0.3.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (0.4.1)
Requirement already satisfied: ipylab in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (1.1.0)
Requirement already satisfied: jupytext in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (1.19.5)
Requirement already satisfied: wrapt in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (2.3.0)
Requirement already satisfied: python-on-whales in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (0.81.0)
Requirement already satisfied: nbconvert in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from otter-grader==5.5.0) (7.17.1)
Requirement already satisfied: docutils in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from fica>=0.3.1->otter-grader==5.5.0) (0.21.2)
Requirement already satisfied: sphinx in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from fica>=0.3.1->otter-grader==5.5.0) (7.4.7)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from astunparse->otter-grader==5.5.0) (0.48.0)
Requirement already satisfied: six<2.0,>=1.6.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from astunparse->otter-grader==5.5.0) (1.17.0)
Requirement already satisfied: packaging>=24.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from wheel<1.0,>=0.23.0->astunparse->otter-grader==5.5.0) (26.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipywidgets->otter-grader==5.5.0) (4.0.15)
Requirement already satisfied: comm>=0.1.3 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipywidgets->otter-grader==5.5.0) (0.2.3)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipywidgets->otter-grader==5.5.0) (3.0.16)
Requirement already satisfied: traitlets>=4.3.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipywidgets->otter-grader==5.5.0) (5.15.1)
Requirement already satisfied: pexpect>4.3 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (4.9.0)
Requirement already satisfied: stack-data in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (0.6.3)
Requirement already satisfied: decorator in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (5.3.1)
Requirement already satisfied: pygments>=2.4.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (2.20.0)
Requirement already satisfied: typing-extensions in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (4.16.0)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (3.0.52)
Requirement already satisfied: matplotlib-inline in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (0.2.2)
Requirement already satisfied: exceptiongroup in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from ipython->otter-grader==5.5.0) (0.19.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jedi>=0.16->ipython->otter-grader==5.5.0) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from pexpect>4.3->ipython->otter-grader==5.5.0) (0.7.0)
Requirement already satisfied: wcwidth in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->otter-grader==5.5.0) (0.8.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jinja2->otter-grader==5.5.0) (3.0.3)
Requirement already satisfied: mdit-py-plugins in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jupytext->otter-grader==5.5.0) (0.4.2)
Requirement already satisfied: markdown-it-py>=1.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jupytext->otter-grader==5.5.0) (3.0.0)
Requirement already satisfied: tomli in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jupytext->otter-grader==5.5.0) (2.4.1)
Requirement already satisfied: mdurl~=0.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from markdown-it-py>=1.0->jupytext->otter-grader==5.5.0) (0.1.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (0.10.2)
Requirement already satisfied: bleach[css]!=5.0.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (6.2.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (1.5.1)
Requirement already satisfied: defusedxml in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (0.7.1)
Requirement already satisfied: importlib-metadata>=3.6 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (8.7.1)
Requirement already satisfied: jupyter-core>=4.7 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (5.8.1)
Requirement already satisfied: jupyterlab-pygments in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (0.3.0)
Requirement already satisfied: beautifulsoup4 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbconvert->otter-grader==5.5.0) (4.15.0)
Requirement already satisfied: webencodings in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from bleach[css]!=5.0.0->nbconvert->otter-grader==5.5.0) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from bleach[css]!=5.0.0->nbconvert->otter-grader==5.5.0) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from importlib-metadata>=3.6->nbconvert->otter-grader==5.5.0) (3.23.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jupyter-core>=4.7->nbconvert->otter-grader==5.5.0) (4.4.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbclient>=0.5.0->nbconvert->otter-grader==5.5.0) (8.6.3)
Requirement already satisfied: pyzmq>=23.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert->otter-grader==5.5.0) (27.1.0)
Requirement already satisfied: tornado>=6.2 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert->otter-grader==5.5.0) (6.5.8)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert->otter-grader==5.5.0) (2.9.0.post0)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbformat->otter-grader==5.5.0) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from nbformat->otter-grader==5.5.0) (4.25.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->otter-grader==5.5.0) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->otter-grader==5.5.0) (0.27.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->otter-grader==5.5.0) (2025.9.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from jsonschema>=2.6->nbformat->otter-grader==5.5.0) (26.1.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from beautifulsoup4->nbconvert->otter-grader==5.5.0) (2.8.4)
Requirement already satisfied: tzdata>=2022.7 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from pandas->otter-grader==5.5.0) (2026.3)
Requirement already satisfied: pytz>=2020.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from pandas->otter-grader==5.5.0) (2026.3.post1)
Requirement already satisfied: numpy>=1.22.4 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from pandas->otter-grader==5.5.0) (2.0.2)
Requirement already satisfied: pydantic!=2.0.*,<3,>=2 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from python-on-whales->otter-grader==5.5.0) (2.13.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from pydantic!=2.0.*,<3,>=2->python-on-whales->otter-grader==5.5.0) (0.4.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from pydantic!=2.0.*,<3,>=2->python-on-whales->otter-grader==5.5.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from pydantic!=2.0.*,<3,>=2->python-on-whales->otter-grader==5.5.0) (2.46.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from requests->otter-grader==5.5.0) (2026.7.22)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from requests->otter-grader==5.5.0) (3.5.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from requests->otter-grader==5.5.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from requests->otter-grader==5.5.0) (2.6.3)
Requirement already satisfied: sphinxcontrib-qthelp in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (2.0.0)
Requirement already satisfied: snowballstemmer>=2.2 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (3.1.1)
Requirement already satisfied: sphinxcontrib-devhelp in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (2.1.0)
Requirement already satisfied: babel>=2.13 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (2.18.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (2.0.0)
Requirement already satisfied: imagesize>=1.3 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (1.5.0)
Requirement already satisfied: alabaster~=0.7.14 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (0.7.16)
Requirement already satisfied: sphinxcontrib-jsmath in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (1.0.1)
Requirement already satisfied: sphinxcontrib-applehelp in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from sphinx->fica>=0.3.1->otter-grader==5.5.0) (2.0.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from stack-data->ipython->otter-grader==5.5.0) (3.0.2)
Requirement already satisfied: executing>=1.2.0 in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from stack-data->ipython->otter-grader==5.5.0) (2.2.1)
Requirement already satisfied: pure-eval in /Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages (from stack-data->ipython->otter-grader==5.5.0) (0.2.3)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/ayushthasale07/Sarg<3/Data8/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.
[Errno 2] No such file or directory: '/content/gdrive/MyDrive/colab-materials-data8-notebooks/materials-sp22-colab/hw/hw05/'
/Users/ayushthasale07/Sarg<3/Data8/homwork/hw05

/Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages/IPython/core/magics/osm.py:393: UserWarning: using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})

# Homework 5: Applying Functions and Iteration

Please complete this notebook by filling in the cells provided. Before you begin, execute the previous cell to load the provided tests.

**Helpful Resource:**
- [Python Reference](http://data8.org/sp22/python-reference.html): Cheat sheet of helpful array & table methods used in Data 8!

**Recommended Readings**: 

* [Tabular Thinking Guide](https://drive.google.com/file/d/13HaWu4rrjeowEOs6S_vaQGM3GremzXQ3/view?usp=sharing)
* [Applying Functions](https://www.inferentialthinking.com/chapters/08/1/Applying_a_Function_to_a_Column.html)
* [Conditionals](https://www.inferentialthinking.com/chapters/09/1/Conditional_Statements.html)
* [Iteration](https://www.inferentialthinking.com/chapters/09/2/Iteration.html)

Please complete this notebook by filling in the cells provided. Before you begin, execute the following cell to setup the notebook by importing some helpful libraries. Each time you start your server, you will need to execute this cell again.

For all problems that you must write explanations and sentences for, you **must** provide your answer in the designated space. **Moreover, throughout this homework and all future ones, please be sure to not re-assign variables throughout the notebook!** For example, if you use `max_temperature` in your answer to one question, do not reassign it later on. Otherwise, you will fail tests that you thought you were passing previously!


**Note: This homework has hidden tests on it. That means even though the tests may say 100% passed, it doesn't mean your final grade will be 100%. We will be running more tests for correctness once everyone turns in the homework.**


Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. 

You should start early so that you have time to get help if you're stuck.

## 1. 2021 Cal Football Season

In [2]:
# Run this cell to set up the notebook, but please don't change it.

# These lines import the numpy and datascience modules.
import numpy as np
from datascience import *
import warnings
warnings.simplefilter('ignore', FutureWarning)

/Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

James is trying to analyze how well the Cal football team performed in the 2021 season. A football game is divided into four periods, called quarters. The number of points Cal scored in each quarter and the number of points their opponent scored in each quarter are stored in a table called `cal_fb.csv`.

In [3]:
# Just run this cell
# Read in the cal_fb csv file
games = Table().read_table("cal_fb.csv")
games.show()

Let's start by finding the total points each team scored in a game.

**Question 1.** Write a function called `sum_scores`.  It should take four arguments, where each argument represents integers corresponding to the team's score for each quarter. It should return the team's total score for that game. **(20 Points)**

*Note:* Don't overthink this question!

In [5]:
def sum_scores(a, b, c, d):
    '''Returns the total score calculated by adding up the score of each quarter'''
    # return np.sum(a, b, c, d)
    return a + b + c + d

sum_scores(14, 7, 3, 0) #DO NOT CHANGE THIS LINE

24

In [6]:
grader.check("q1_1")

q1_1 results: All test cases passed!

**Question 2.** Create a new table `final_scores` with three columns in this *specific* order: `Opponent`, `Cal Score`, `Opponent Score`. You will have to create the `Cal Score` and `Opponent Score` columns. Use the function `sum_scores` you just defined in the previous question for this problem. **(20 Points)**

*Hint:* If you want to apply a function that takes in multiple arguments, you can pass multiple column names as arguments in `tbl.apply()`. The column values will be passed into the corresponding arguments of the function. Take a look at the Python Reference Sheet and Lecture 13's demo for syntax.

*Note:* If you’re running into issues creating `final_scores`, check that `cal_scores` and `opponent_scores` output what you want.

In [10]:
cal_scores = games.column("Cal 1Q") + games.column("Cal 2Q") + games.column("Cal 3Q") + games.column("Cal 4Q")
opponent_scores = games.column("Opp 1Q") + games.column("Opp 2Q") + games.column("Opp 3Q") + games.column("Opp 4Q")
final_scores = Table().with_columns(
    "Opponent", games.column("Opponent"),
    "Cal Score", cal_scores,
    "Opponent Score", opponent_scores
)
final_scores

Opponent         | Cal Score | Opponent Score
Nevada           | 17        | 22
TCU              | 32        | 34
Sacramento State | 42        | 30
Washington       | 24        | 31
Washington State | 6         | 21
Oregon           | 17        | 24
Colorado         | 26        | 3
Oregon State     | 39        | 25
Arizona          | 3         | 10
Stanford         | 41        | 11
... (2 rows omitted)

In [11]:
grader.check("q1_2")

q1_2 results: All test cases passed!

We can get specific row objects from a table. You can use `tbl.row(n)` to get the `n`th row of a table. `row.item("column_name")` will allow you to select the element that corresponds to `column_name` in a particular row. Here's an example:

In [12]:
# Just run this cell
# We got the Axe!
games.row(9)

Row(Opponent='Stanford', Cal 1Q=0, Cal 2Q=14, Cal 3Q=13, Cal 4Q=14, Opp 1Q=0, Opp 2Q=3, Opp 3Q=0, Opp 4Q=8)

In [13]:
# Just run this cell
games.row(9).item("Cal 4Q")

14

**Question 3.** We want to see for a particular game whether or not Cal lost. Write a function called `did_cal_lose`.  It should take one argument: a **row object** from the `final_scores` table. It should return either `True` if Cal's score was less than the Opponent's score, and `False` otherwise. **(20 Points)**

*Note 1*: "Row object" means a row from the table that contains all the data for that specific row. It is **not** the index of a row. Do not try and call `final_scores.row(row)` inside of the function.

*Note 2*: If you're still confused by row objects, try printing out `final_scores.row(1)` in a new cell to visually see what it looks like! This piece of code is pulling out the row object located at index 1 of the `final_scores` table and returning it. When you display it in a cell, you'll see that it is not located within a table, but is instead a standalone row object!

In [14]:
def did_cal_lose(row):
    return row.item("Cal Score") < row.item("Opponent Score")

did_cal_lose(final_scores.row(1)) #DO NOT CHANGE THIS LINE

True

In [15]:
grader.check("q1_3")

q1_3 results: All test cases passed!

**Question 4.** James wants to see how Cal did against every opponent during the 2021 season. Using the `final_scores` table:

1. Assign `results` to an array of `True` and `False` values that correspond to whether or not Cal lost.
2. Add the `results` array to the `final_scores` table in a column named `Results`, and assign this to `final_scores_with_results`.
3. Then, respectively assign the number of wins and losses Cal had to `cal_wins` and `cal_losses`.

**(20 Points)**

*Hint 1*: `True` and `False` are **not** strings. What data type are they?

*Hint 2*: `tbl.num_rows` might be helpful too.

*Hint 3*: When you only pass a function name and no column labels through `tbl.apply()`, the function gets applied to every row in `tbl`.

In [16]:
results = final_scores.column("Cal Score") < final_scores.column("Opponent Score")
final_scores_with_results = final_scores.with_column("Results", results)
cal_losses = np.sum(results)
cal_wins = final_scores.num_rows - cal_losses

# Don't delete or edit the following line:
print(f"In the 2021 Season, Cal Football won {cal_wins} games and lost {cal_losses} games. Go Bears! 🐻")

In the 2021 Season, Cal Football won 5 games and lost 7 games. Go Bears! 🐻

In [17]:
grader.check("q1_4")

q1_4 results: All test cases passed!

**Question 5:** Sometimes in football the two teams are equally matched and the game is quite close. Other times, it is a blowout, where the winning team wins by a large margin of victory. Let's define a **big win** to be a game in which the winning team won by more than 10 points.

Use your `final_scores` table to assign `big_wins` to an array of team names that Cal had big wins against during the 2021 football season. You may find the `is_big_win` function defined below helpful to you! **(20 Points)**

In [23]:
def is_big_win(row):
    '''Return a boolean to describe whether or not a game (row) is a big win'''
    score_diff = row.item("Cal Score") - row.item("Opponent Score")
    
    if score_diff > 10:
        return True
    else:
        return False

big_wins = make_array()

for row in final_scores.rows: # This will help us iterate through rows of final_scores table
    opponent = row.item(0)
    if np.abs(row.item(1) - row.item(2)) > 10: # You should use the function defined above!
        big_wins = np.append(big_wins, opponent) # Do not change this line - Adds character to the end of some_string
big_wins

for row in final_scores.rows:
    print(row)

Row(Opponent='Nevada', Cal Score=17, Opponent Score=22)
Row(Opponent='TCU', Cal Score=32, Opponent Score=34)
Row(Opponent='Sacramento State', Cal Score=42, Opponent Score=30)
Row(Opponent='Washington', Cal Score=24, Opponent Score=31)
Row(Opponent='Washington State', Cal Score=6, Opponent Score=21)
Row(Opponent='Oregon', Cal Score=17, Opponent Score=24)
Row(Opponent='Colorado', Cal Score=26, Opponent Score=3)
Row(Opponent='Oregon State', Cal Score=39, Opponent Score=25)
Row(Opponent='Arizona', Cal Score=3, Opponent Score=10)
Row(Opponent='Stanford', Cal Score=41, Opponent Score=11)
Row(Opponent='UCLA', Cal Score=14, Opponent Score=42)
Row(Opponent='USC', Cal Score=24, Opponent Score=14)

In [24]:
grader.check("q1_5")

q1_5 results: All test cases passed!

You're done with the required section of Homework 5! Continue on to the optional section for some more practice with iterations and for loops.

Make sure to **run the submit cell located at the bottom of this notebook.**

## 2. Unrolling Loops (Optional)

**This section of HW5 is optional. Do it for your own practice, but it will not be incorporated into the final grading!**

"Unrolling" a `for` loop means to manually write out all the code that it executes.  The result is code that does the same thing as the loop, but without the structure of the loop.  For example, for the following loop:

    for num in np.arange(3):
        print("The number is", num)

The unrolled version would look like this:

    print("The number is", 0)
    print("The number is", 1)
    print("The number is", 2)


Unrolling a `for` loop is a great way to understand what the loop is doing during each step. In this exercise, you'll practice unrolling a `for` loop.


In the question below, write code that does the same thing as the given code, but with any `for` loops unrolled.  It's a good idea to run both your answer and the original code to verify that they do the same thing.  (Of course, if the code does something random, you'll get a different random outcome than the original code!)

**Optional Question 1.** Unroll the code below.

In [ ]:
for joke_iteration in np.arange(3):
    print("Knock, knock.")
    print("Who's there?")
    print("Banana.")
    print("Banana who?")
print("Knock, knock.")
print("Who's there?")
print("Orange.")
print("Orange who?")
print("Orange you glad I didn't say banana?")

In [ ]:
...

Congratulations, you are done with Homework 5!

**Important submission steps:** 
1. Run the tests and verify that they all pass.
2. Choose **Save Notebook** from the **File** menu, then **run the final cell**. 
3. Click the link to download the zip file.
4. Then submit the zip file to the corresponding assignment according to your instructor's directions. 

**It is your responsibility to make sure your work is saved before running the last cell.**

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export(pdf=False, run_tests=True)