In [1]:
from datascience import *
import numpy as np

/Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [5]:
nba_pg_2020 = Table.read_table("nba_salaries.csv").where("season", 2020).drop("season")

In [6]:
nba_pg_2020

rank | name              | position | team                  | salary
1    | Stephen Curry     | PG       | Golden State Warriors | 40231758
2    | Chris Paul        | PG       | Oklahoma City Thunder | 38506482
3    | Russell Westbrook | PG       | Houston Rockets       | 38506482
4    | John Wall         | PG       | Washington Wizards    | 38199000
5    | Kevin Durant      | SF       | Brooklyn Nets         | 38199000
6    | James Harden      | SG       | Houston Rockets       | 38199000
7    | LeBron James      | SF       | Los Angeles Lakers    | 37436858
8    | Kyle Lowry        | PG       | Toronto Raptors       | 34996296
9    | Blake Griffin     | PF       | Detroit Pistons       | 34449964
10   | Tobias Harris     | SF       | Philadelphia 76ers    | 32742000
... (518 rows omitted)

In [11]:
warriors = (
    nba_pg_2020
    .where("team", "Golden State Warriors")
    .drop("team")
    .relabeled("salary", "$"))
warriors.show(3)

In [12]:
salary = warriors.column("$")

In [13]:
salary.sum()

106010951

In [14]:
salary.max()

40231758

In [16]:
salary.item(0)

40231758

In [17]:
suns = (
    nba_pg_2020
    .where("team", "Phoenix Suns")
    .drop("team")
    .relabeled("salary", "$")
)

In [18]:
warriors.column("$").sum() - suns.column("$").sum()

-3455154

In [21]:
warriors.column("$").mean()

8154688.538461538

In [22]:
suns.column("$").mean()

5761373.9473684207

In [23]:
8154688.538461538 - 5761373.9473684207

2393314.5910931174

In [25]:
warriors.num_rows
suns.num_rows

19

In [26]:
warriors.take(1)

rank | name          | position | $
13   | Klay Thompson | SG       | 32742000

In [29]:
warriors.take(np.arange(0, warriors.num_rows))

rank | name                | position | $
1    | Stephen Curry       | PG       | 40231758
13   | Klay Thompson       | SG       | 32742000
60   | Draymond Green      | PF       | 18539130
223  | Kevon Looney        | PF       | 4464226
316  | Willie Cauley-Stein | C        | 2177483
332  | Jordan Poole        | SG       | 1964760
339  | Omari Spellman      | PF       | 1897800
496  | Alen Smailagic      | PF       | 898310
497  | Eric Paschall       | PF       | 898310
502  | Damion Lee          | SG       | 842327
... (3 rows omitted)