In [1]:
from datascience import *
import numpy as np

/Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [4]:
welcome = Table.read_table("welcome_survey_sp22.csv")
welcome.show(5)

In [13]:
on_the_side = welcome.where("Sleep position", are.containing("side"))

In [14]:
on_the_side.show(5)

In [15]:
on_the_side.column("Hours of sleep").mean()

7.1131167268351385

In [16]:
np.sum(welcome.column("Hours of sleep") >= 8)

473

In [17]:
full = Table.read_table("nc-est2019-agesex-res.csv")

In [18]:
full.show(5)

In [25]:
partial = full.select("AGE", "SEX", "POPESTIMATE2014", "POPESTIMATE2019")
partial.show(5)

In [26]:
us_pop = partial.relabeled("POPESTIMATE2014", "2014").relabeled("POPESTIMATE2019", "2019")
us_pop.show(5)

In [31]:
us_pop.where("AGE", are.above_or_equal_to(80)).sort("AGE").select(1,0,2,3)

SEX  | AGE  | 2014    | 2019
0    | 80   | 1263540 | 1475278
1    | 80   | 539342  | 643638
2    | 80   | 724198  | 831640
0    | 81   | 1215634 | 1381641
1    | 81   | 510456  | 593628
2    | 81   | 705178  | 788013
0    | 82   | 1152926 | 1241341
1    | 82   | 476098  | 525766
2    | 82   | 676828  | 715575
0    | 83   | 1089054 | 1151190
... (56 rows omitted)