In [1]:
from datascience import *
import numpy as np

import matplotlib.pyplot as plt

%matplotlib inline

/Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [6]:
united = Table.read_table("united.csv")
united = united.with_column("Row", np.arange(united.num_rows)).move_to_start("Row")
united.show(5)

In [7]:
united.where("Destination", "JFK")

Row  | Date   | Flight Number | Destination | Delay
26   | 6/1/15 | 502           | JFK         | -4
33   | 6/1/15 | 637           | JFK         | 141
39   | 6/1/15 | 704           | JFK         | -8
50   | 6/1/15 | 758           | JFK         | -5
51   | 6/1/15 | 760           | JFK         | 352
56   | 6/1/15 | 824           | JFK         | 3
57   | 6/1/15 | 898           | JFK         | 290
179  | 6/2/15 | 502           | JFK         | 0
188  | 6/2/15 | 637           | JFK         | 202
194  | 6/2/15 | 704           | JFK         | -11
... (593 rows omitted)