In [1]:
from datascience import *
import numpy as np

import matplotlib.pyplot as plt

%matplotlib inline

/Users/ayushthasale07/Sarg<3/Data8/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
# Average
l = [1, 2, 3, 5]

np.mean(l)

2.75

In [3]:
values = make_array(2, 3, 3, 9)

In [4]:


sd_table = Table().with_columns('Value', values)
sd_table

Value
2
3
3
9

In [5]:
average_value = np.mean(values)
average_value

4.25

In [6]:
deviations = values - average_value
sd_table = sd_table.with_column('Deviation', deviations)
sd_table

Value | Deviation
2     | -2.25
3     | -1.25
3     | -1.25
9     | 4.75

In [7]:
sum(deviations)

0.0

In [8]:
sd_table = sd_table.with_column('Squared Deviation', deviations ** 2)
sd_table

Value | Deviation | Squared Deviation
2     | -2.25     | 5.0625
3     | -1.25     | 1.5625
3     | -1.25     | 1.5625
9     | 4.75      | 22.5625

In [10]:
variance = np.mean(sd_table.column("Squared Deviation"))
variance

7.6875

In [11]:
sd = variance**0.5
sd

2.7726341266023544

In [12]:
np.std(values)

2.7726341266023544